### ISSUE TITLE
Constant memory in jitified kernels

### ISSUE THREAD

**Issue by qavl** [NVIDIA/jitify#25]
Hi!
I have a template kernel which also uses constant memory. Can I somehow make this constant memory visible for a kernel if I use jitify for its instantiation?

Thank you

**Comment by maddyscientist** [comment]
Hi @qavl 

I prototyped how to do this in jitify, though my implementation wasn't very robust when the `__constant__` memory declarations were located in a namespace.  Since then, CUDA 10.1 has added support for looking up the name of `__constant__` variables which would easily allow us to add robust support for this in Jitify.  I've had it on my todo list for a while to get this done, so it's good to have someone asking for it 😄

I can try to get to this in the next few weeks.  Would the constraint of requiring CUDA 10.1 or above be acceptable?
