### ISSUE TITLE
Question: Linking RTC code with executing program

### ISSUE THREAD

**Issue by Robadob** [NVIDIA/jitify#46]
If the executing program has been compiled with `-rdc=true`, is it possible to link RTC compiled code with this so that it has access to shared symbols (`__device__`, `__constant__`)?

Small example of what I mean here: (Tested in Visual Studio 2015)
https://gist.github.com/Robadob/b2b7704a36e2f679942e854a0f41082a

I've found that [`cuLinkAddFile()`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MODULE.html#group__CUDA__MODULE_1g1224c0fd48d4a683f3ce19997f200a8c) would need to be used.

However it's not clear how that could be used to link with the executing program (and whether also building the executing program to fatbin/similar for linking would be useful).

**Comment by Robadob** [comment]
Have just found [`CU_JIT_GLOBAL_SYMBOL`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1g5527fa8030d5cabedc781a04dbd1997d) enums, which looks like they might be a less dynamic way of achieving this.

**Comment by benbarsdell** [comment]
Unfortunately it is not possible for runtime code to gain access to symbols in the host program.

Jitify does support two related things that may be useful:

1. Linking external device libraries using `-Lpath` and `-lname` options. We could potentially extend this to support linking with ptx/cubin/object files as well if that would be useful.
2. Accessing `__device__` and `__constant__` variables declared inside the runtime code via `kernel_instantiation.get_constant_ptr()` (we will be extending this to support accessing `__device__` variables as well soon).

I'm not very familiar with the CU_JIT_GLOBAL_SYMBOL flags, but it looks like they're used to make extern symbols in the runtime code use host addresses instead of looking for device symbols during linking. Is there a reason this is useful for your application vs. say using non-extern symbols in your runtime code and accessing them via get_constant_ptr?

**Comment by Robadob** [comment]
I'm working with @mondus.

We're developing a new framework for developing complex system simulations, whilst abstracting away most of the CUDA (FLAMEGPU2, to improve on usability over [FLAMEGPU](http://www.flamegpu.com/)). He's also interested in developing a runtime compiled Python interface to the library, to make it more accessible, which is where this comes in. (I'm not sure if he told you this much the other day)

> Accessing `__device__` and `__constant__` variables ...

Several common reused items/pointers are stored behind `__device__` and `__constant__` variables, hence automatic linking with the executing runtime would be convenient. There are several workarounds, such as reducing the number of symbols (by packing items inside a struct) and then manually setting the symbols inside the RTC units as each is compiled (using `get_constant_ptr` or similar, I hadn't noticed this, but it will require some changes to reduce the number of items we need to set). 

One potential downside of this would be that duplicating symbols would inflate constant cache usage, as we're using a large portion of constant cache for a hashtable central to accessing variables within models. For potentially large models with many RTC device functions, this could lead to capacity issues.

But that's a long way off at the stage, so I don't think it's a killer problem.

> Linking external device libraries using `-Lpath` and `-lname` options. ...

At this point I'm not sure how viable it would be to load the entire library from PTX at runtime, as from my understanding that would necessitate require changing large parts of the codebase that interact with CUDA.

I'm assuming, if we built the library a second time to ptx/cubin, and linked against that, it wouldn't also link against the runtime. So your second suggestion is likely the way to go.

Thanks for the advice.

**Comment by Robadob** [comment]
@benbarsdell 
P.S. could you please add `#include <cctype>` to `jitify.hpp`, it doesn't build without this under Visual Studio 2015, due to `isdigit` and `isalpha` (removing `std::` from them also works but that's probably a less portable solution).
