### ISSUE TITLE
Support C++ 17 

### ISSUE THREAD

**Issue by kotbegemot** [NVIDIA/jitify#60]
Can use NVRTC in a C ++ 17 codebase?

**Comment by benbarsdell** [comment]
NVRTC and NVCC do not yet support C++17, but there shouldn't be any problem using NVRTC to compile C++14 device code in a project that uses a C++17 host compiler.
E.g., jitify_example.cpp compiles fine with `g++ -std=c++17`.

**Comment by kotbegemot** [comment]
what are the limitations of this approach?

**Comment by benbarsdell** [comment]
Just that you can't (yet) compile CUDA device code with c++17. The device code and any headers it uses will need to be at most c++14. The presence of c++17 headers on the host shouldn't be a problem because Jitify already avoids them. However, you may need to be careful to avoid problems due to different ABIs when passing data between the host and device code.

**Comment by kotbegemot** [comment]
Where to see good and bad use cases?
